### ISSUE TITLE
"Save" Clarifications

### ISSUE THREAD

**Issue by chasemaier** [xyonix/vannot#19]
I'm interested to get some insight into the reasons for the current implementation of saving image frames. Seems to be somewhat difficult to work with / inefficient as-is -- wondering if I'm missing something.

Possible questions to start with:
* Why are base64-encoded images used rather than traditional image formats?
* Why is the image data itself included in the JSON state if the application does not want it back as part of the state?
* If you annotate a frame that has already been recorded, it will send it again, even if it has already been uploaded. Is that intended?

---

If the image data was going to be exported, I guess I'd envision something more like....

- Results are saved as a mutli-part form post with the JSON payload as the body of the request.
- Any new image frames would be attached as JPEG files in their native format, indexed by their frame number. E.g. `frame[237]` in the multi-part POST would be the jpeg file of the frame, just as if you included it via a `<input type="file" />` element. Having to transmit in and coerce the images to/from a base-64 format seem unnecessary and inefficient, especially since then the server must remove this data from the JSON state prior to persisting it.
- The JSON state would include a persistent list of `exportedFrames: [..., ..., 237, ...]` integer frame numbers which would prevent sending duplicate frames unnecessarily across sessions.
- The response from the POST from the server should immediately become the new current state.
- If the server does not respond successfully, it should be possible to "try again" rather than just losing all the data after the failed submit.

Alternatively, instead of sending the frame data with every save, the application could send the state to a URL (same json data as saveUrl). The server could identify the newly identified frames compared to what it had stored and respond with a list of frame-specific pre-signed URLs where each frame could be uploaded to on the client side directly.

**Comment by clint-tseng** [comment]
The background is that prior to my involvement in this project, I am told there were significant troubles deterministically retrieving the expected frame from a video given a timecode. Personally, I do have knowledge that despite .mp4's absolute sample lookup tables (which should definitively prevent such problems as they point to exact byte ranges), ffmpeg does a lot of nasty guesswork trickery to try to "just work"/"just play" as quickly as possible. So this is the likely source of such troubles.

As such, part of the specification I have been building against included a feature for video frame image export from the client tool, so that the same tool annotating the image was the one recording permanently which frame that image was from.

As for the more specific questions you have:

* **Why base64?** I wanted to limit as much as possible assumptions about the server API (ie avoid multiple endpoints), and I was mostly focused on proof-of-concepting that the feature could work at all. I'm not attached to it, and provided I can figure out how to formulate the multipart POST instead (likely) it seems like a very reasonable solution (albeit multipart POSTs are often annoying to handle on the server side, of course). That said, it _is_ a traditional image format (JPEG), just encoded in base64 to reside in the JSON envelope.
* **Why send it if the application does not want it back?** I was operating under the advice that the server needed to have this data, even though the client does not.
* **Why does the same frame get sent multiple times?** Must be a regression; [this line](https://github.com/xyonix/vannot/blob/master/project/src/viewmodel/io.js#L41) is meant to only send newly-annotated frames, and it used to work. Pending our broader discussion about the presence of this machinery, I will take a look at why it's doing that. It's possible your issues with #17 were triggering this apparent behaviour, as failed saves will not checkpoint the data for that delta.

And as for your list of suggestions:

* **Multipart POST**: a highly reasonable approach.
* **Therefore images as binary**: yes.
* **Track already-sent images**: theoretically this already exists (as the client can tell the delta between the annotated-frames at load and at save). Some bug is keeping that from functioning.
* **Response from POST becoming the new state**: sounds like a reasonable ask but I'm not sure what it has to do with the ticket at hand (besides updating the tracking of which images have been exported in case someone else has saved in the meantime?)
* **Try again on failure**: pressing Save again should do this? What are you seeing instead?

Again, I'm not attached to anything already-written here—what exists is very preliminary.

**Comment by chasemaier** [comment]
Thanks!

I've been able to integrate with it as-is. I think the changes I describe may be good to incorporate should that functionality ever become revisited by changes/other features in the future.

Some final though:
* I have the back-end persisting the stored/captured frames into the object state. So even if that isn't being used I have it in my instance at least, which I find to be a good addition.
* Part of my concern with the base64-encoded images is the fact that AWS's API Gateway (which we are using) has a 10MB limit for a request and that'll increase the payload size for sure -- which may impose an upper limit at some point on how many frames could be annotated in one "session" -- but we're not there yet (I've been testing against a very low resolution video). Maybe at the very least we may need to look at batching the save process if we find we reach that limit (e.g. post the same JSON with different image data several times for each "batch" of < 10MB of frames). I'll follow up if we run into this.
* Yeah, i think the response result becoming the new state would be a good change -- just a good opportunity to be sure the server and client are in sync. Not critical.
* Regarding "Try again on failure" -- I believe I was seeing that it would post the JSON state again if the first POST failed, but would not send the image frame data if the request where it initially tried to send it failed. So we'd get the JSON data, but the frame image data would be lost in that instance. That's what I recall -- but I'd need to test again to verify that is actually (still) accurate.

**Comment by clint-tseng** [comment]
okay—i've fixed some issues with the checkpointing, so when imagedata is/isn't sent should reflect expectation now, and i've changed the save request to a multipart POST; see the README changes for details on that.

i've also created a new ticket #21 to track what we were discussing about absorbing new server state. i'm holding off on it for now: it didn't sound urgent and it's probably worth a deeper look into ramifications, especially if the goal is in part to support multiple users (which i had been advised was out of scope for now, since it's naturally quite complex).

with all that, i believe this ticket may be closed.
