### ISSUE TITLE
Points can be placed out of the bounds of the image

### ISSUE THREAD

**Issue by chasemaier** [xyonix/vannot#20]

**Comment by clint-tseng** [comment]
So, this is actually highly intentional—it is much easier to trace shapes that clip on the edge of the video frame if points outside image bounds are allowed, especially when trying to adjust for deltas between keyframes.

If still desired, I can of course change the behaviour, or make it an option.

Alternatively, I can include some kind of data export that clips all polygons to the frame at final export.

**Comment by chasemaier** [comment]
Yeah, IMO, as long as the exported polygons respect the image boundaries, that seems sufficient.

**Comment by chasemaier** [comment]
Hmm. I guess without playing with it with the boundary restriction in place, I'm having a hard time seeing what difficulty that imposes like you describe in your original comment.

E.g. it seems like after placing a point outside the bounds of an image if it snapped to the nearest image border, I can't see how that would disrupt my input process -- but I could definitely be missing something.

For example, I'd imagine this....

![image](https://user-images.githubusercontent.com/2565985/39949355-3dc11b72-552f-11e8-8244-03be55a47954.png)

... would collapse into ...

![image](https://user-images.githubusercontent.com/2565985/39949422-932b0bd6-552f-11e8-805f-1c61cbbcebf5.png)

... once it was no longer active / points were final.

I agree that having two different sets of data points would be a bad plan -- I had envisioned only one set of polygon points -- once the point was placed or the shape was final it would just adjust to fit within the image bounds.

Given that the tool is designed to mark regions **_within images_**, I don't know what value we'd get from persisting the polygon data for regions to extend past the image bounds.

We haven't yet attempted to make use of the polygon data that is exported, so I'm mostly just assuming things about problems having the points outside the image bounds will cause in the future.

Similarly, on an unrelated note, I'm not sure if we should allow polygons with overlapping lines, such as:

![image](https://user-images.githubusercontent.com/2565985/39949500-ee3a8f42-552f-11e8-9c85-d4f1d918e146.png)

Seems like producing such masks wouldn't be useful in most any scenario i can think of, so maybe we should:
* Prevent it?
* Break it up into 3 distinct polygons at the intersections?

**Comment by clint-tseng** [comment]
(Re: self-crossing polygons: yeah, I think the natural solution is to just make it into as many polygons as there are area segments.)

Well, I've been drawing on canvases as a graphics designer for decades now and I feel strongly that being able to draw outside the frame is a huge help for getting things to line up, etc, and especially when editing an existing shape (rarely does one trace a shape perfectly on the first pass; there are usually little tweaks one has to do after the polygon is laid down) or one that's been copied from a previous frame (for instance in your pasted example see how now I have to adjust 6 separate vertices instead of just 3). Working on exactly the frame boundary is also a really big kinematic and visual hassle, and being able to place the vertices away from that clutter is very ergonomically beneficial.

On the other hand, I'm happy to do whatever, and I feel like the best path might be to just implement what you're saying as a toggle option and see how you feel about it in actual usage.

Also, I'm going to edit out your images as this is a publicly accessible repository.

**Comment by clint-tseng** [comment]
Okay, so I started implementing this as an experimental flag for you, but it's actually quite involved to fully implement even shoddily, and some of the behavior isn't very obvious to me:

* **Nontrivial cases** (in no particular order, and written partially just to document for myself):
    * Dragging one or more specific selected points: upon clip (ie drag or drag-release; see below), need to assess frame boundaries, do polygon clipping, _and_ track which pre-clip points relate to which post-clip points so that the appropriate points are reselected after the clipping operation.
        * Makes it difficult to use a pre-rolled 3rd party polygon math library as they tend to expect pointdata in particular data structures (ie `Vec2`) which would eliminate our ability to just compare references before/after.
    * Need to handle cases where clipping causes a polygon to become two.
* **Unclear behaviour**
    * Dragging a shape off the canvas: does it just disappear?
    * The Duplicate selected shapes operation shifts the clones down and right to make visually clear that the operation has occurred (as is standard with such operations). But this can cause undesired clipping at the frame boundaries that would then require manual reconstruction of lost data. Do we just do it anyway?

Obviously, all these problems and questions are totally solvable, and I am happy to do so if you still wish to pursue this path. Typically, when questions like this come up I prefer to just rig the proposal up so you can decide for yourself. However, since the experiment is much more costly than I'd anticipated I wanted to double-check with you again before proceeding with it.

I'd also like to provide three additional observations:

* "Given that the tool is designed to mark regions within images, I don't know what value we'd get from persisting the polygon data for regions to extend past the image bounds." But this is true also of eg Photoshop/Illustrator documents: only the visible canvas is relevant to the final rendered image. These tools still allow vector shapes to exceed the bounds. So the logic doesn't carry across to analogous tools.
* Relatedly, the point in time at which clipping occurs is a momentous decision:
    * Continuous/interactive clipping with every mousemove is the moment of least surprise: the application teaches the user immediately and unambiguously that only the canvas area is valid drawing space. But it's also the most destructive: accidentally brushing a canvas edge mid-drag, for example, will quash the shape.
    * Clipping after each operation (ie on mouseup) is the moment of second-least surprise: the application teaches the user relatively early and somewhat frequently that only the canvas area is valid space. It's somewhat forgiving to mid-drag input errors, but the user still potentially loses data on mouseup, particularly if they forget that the clip will occur.
    * Clipping on deselect is the moment of most surprise: the application gives no indication that clipping will occur until the user goes through potentially many operations, possibly including the initial drawing and then subsequent editing of points before deselecting the shape. But misunderstandings aside, it runs little risk of accidental destruction _as long as_ the user remembers this application behaviour and accounts for it in her inputs before deselecting.
        * Also difficult to answer in this case: what if a shape exceeding canvas bounds is selected, and the user _adds_ another shape to the selection?
    * Clipping on export is a moment of _no_ surprise and _no_ destruction: the user's inputs and data are always respected and always preserved—there is no risk in either regard.
* One final observation, which is that now that we do a multipart-POST, we have a somewhat better spot to put export-only data; we can provide a `data.json` field with the current application working data which can round-trip directly, and a separate `export.json` field where we snip apart self-intersecting polygons and perform canvas-area clipping.
    * (As a benefit, if self-intersecting polygons are actually a useful expedient way to produce some particular tracking shape, that operation too gets pushed all the way to export-time, and they get to keep those as well.)

**Comment by chasemaier** [comment]
Sounds like the points out of bounds issue won't be a problem for post-processing.

I'll leave this open to represent the self-crossing polygon situation -- though not a current priority.

**Comment by clint-tseng** [comment]
Okay—I think I'll probably actually close this ticket and open a new one for self-intersecting polygons. Thanks!

**Comment by clint-tseng** [comment]
Closing this in favor of #23.
