### ISSUE TITLE
Instance group classes

### ISSUE THREAD

**Issue by clint-tseng** [xyonix/vannot#25]
We can now group shapes together into instances (#22), but we can't say anything about them besides that they're related. This ticket contains a number of related items that enable applications that need it to assign names or classifications to the instance groups themselves.

- [x] show optional freeform instance name field
  - [x] configuration to show/hide
- [x] configuration option to preset available instance classes
  - [x] configuration to restrict to preset classes
- [x] add autocomplete to freeform instance name field
- [x] possibly allow coloration for preset instance classes

**Comment by clint-tseng** [comment]
okay; everything listed in this ticket is present and ready for testing, feedback, review.

**Comment by chasemaier** [comment]
@clint-tseng Tested this out and looks good for the most part. I'm seeing some problems though with the carry over function.

Clicking the carry over button appears to fail (and produce this console error):
```
Uncaught TypeError: Cannot read property 'class' of undefined
    at instanceIds.map (app.js?1530558521589:56021)
    at Array.map (<anonymous>)
    at drawInstances (app.js?1530558521589:56017)
    at draw (app.js?1530558521589:56237)
    at window.requestAnimationFrame (app.js?1530558521589:56713)
instanceIds.map @ app.js?1530558521589:56021
drawInstances @ app.js?1530558521589:56017
draw @ app.js?1530558521589:56237
window.requestAnimationFrame @ app.js?1530558521589:56713
requestAnimationFrame (async)
(anonymous) @ app.js?1530558521589:56711
(anonymous) @ app.js?1530558521589:56265
emitNone @ app.js?1530558521589:20372
emit @ app.js?1530558521589:20452
set mouse @ app.js?1530558521589:56957
processMouse @ app.js?1530558521589:55449
$document.on @ app.js?1530558521589:55452
dispatch @ app.js?1530558521589:27206
elemData.handle @ app.js?1530558521589:27014
```

While that seems to fail, the objects seem to somehow eventually show up in the frame and on the timeline. It seems like doing a drag/select even on the main canvas causes the object to appear on the canvas, though not on the timeline.

It works as intended, but I did end up switching to the preset drop-down rather than the freeform with default values because the auto-suggest box made it difficult to change between values. E.g. if i selected the wrong value from suggested values, i couldn't expand the dropdown to pick the alternate value without first deleting all the text.

Also probably unrelated from this change -- when trying to draw the very detailed edges of some objects I noticed it was a bit hard to get accurate point positioning and that the points/line elements don't seem to scale with zooming.

E.g. if you zoom in fully it seems like the points don't scale down at all to account for being zoomed in and if the object is detailed/small it becomes difficult to also "see through" to where the points are actually placed: (contrived example)
![image](https://user-images.githubusercontent.com/2565985/42182496-397ef434-7df3-11e8-86ac-9382c903a2d6.png)

**Comment by clint-tseng** [comment]
okay, i pushed a fix for carry over and will create a new ticket for the zoom scaling; that one is worth some discussion.

as for the the auto-suggest behavior, that's all browser-native behavior; i'll look into whether it's adjustable.

**Comment by clint-tseng** [comment]
It doesn't look like the auto-suggest behavior can be changed without implementing our own autocomplete. If it would be substantially useful to have the other behavior, I'm happy to do so.

**Comment by clint-tseng** [comment]
Still happy to looking into alternative autosuggest behavior if something else would work better, but otherwise this is all done, so I'm closing the ticket.
